<a href="https://colab.research.google.com/github/gafurjanoff/Data_Science_/blob/main/03_PANDAS_yakuniy_vazifa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### PANDAS. Yakuniy vazifa. **1-QISM**

In [5]:
import pandas as pd
import numpy as np

In [70]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population.csv", index_col=0)
df

               country     density   densityMi   pop2021     area
rank
1                Macau  21946.4667  56841.3487   658.394       30
2               Monaco  19755.5000  51166.7450    39.511        2
3            Singapore   8305.1915  21510.4461  5896.686      710
4            Hong Kong   6841.3134  17719.0017  7552.810     1104
5            Gibraltar   5616.3333  14546.3033    33.698        6
...                ...         ...         ...       ...      ...
228            Namibia      3.1338      8.1166  2587.344   825615
229     Western Sahara      2.3003      5.9577   611.875   266000
230           Mongolia      2.1286      5.5129  3329.289  1564110
231   Falkland Islands      0.2902      0.7517     3.533    12173
232          Greenland      0.0263      0.0680    56.877  2166086

[232 rows x 5 columns]

### 1-VAZIFA. Yuqoridagi DF ustunlari nomini quyidagi qiymatlarga o'zgartiring va DF yuqorisidan 3 ta davlatni chiqaring
`['davlat','zichlik_km','zichlik_mi','aholi','maydoni']`

In [80]:
df.rename(columns = {'country' : 'davlat', 'density' : 'zichlik_km','densityMi':'zichlik_mi','pop2021' : 'aholi','area':'maydoni'} , inplace  = True )
df.head(3)

df_new  = df

df_new
# df.columns = ['davlat','zichlik_km','zichlik_mi','aholi','maydoni']
# df.head(3)

                davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1                Macau  21946.4667  56841.3487   658.394       30
2               Monaco  19755.5000  51166.7450    39.511        2
3            Singapore   8305.1915  21510.4461  5896.686      710
4            Hong Kong   6841.3134  17719.0017  7552.810     1104
5            Gibraltar   5616.3333  14546.3033    33.698        6
...                ...         ...         ...       ...      ...
228            Namibia      3.1338      8.1166  2587.344   825615
229     Western Sahara      2.3003      5.9577   611.875   266000
230           Mongolia      2.1286      5.5129  3329.289  1564110
231   Falkland Islands      0.2902      0.7517     3.533    12173
232          Greenland      0.0263      0.0680    56.877  2166086

[232 rows x 5 columns]

In [ ]:
#@title To'g'ri javob
df.columns = ['davlat','zichlik_km','zichlik_mi','aholi','maydoni']
df.head(3)

         davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1         Macau  21946.4667  56841.3487   658.394       30
2        Monaco  19755.5000  51166.7450    39.511        2
3     Singapore   8305.1915  21510.4461  5896.686      710

## Yuqoridagi jadval dunyo davlatlarining aholi zichligi bo'yicha reytingini ko'rsatadi.
DF indeksi sifatida davlatning zichlik reytingi olingan (aholi eng zich yashaydigan davlatlar yuqorida).

**Ustunlar:**

`davlat` - Davlat nomi

`zichlik_km` - har 1 kv.km. ga to'g'ri keluvchi aholi soni

`zichlik_mi` - har 1 kv.milyaga to'g'ri keluvchi aholi soni (milya - AQSh masofa o'lchov birligi)

`aholi` - 2021-yilga ko'rsa aholi soni (ming)

`maydoni` - davlat maydoni (kv.km)

### 2-VAZIFA. DF oxiridan 10 ta qator chiqaring.

In [18]:
df.tail(10)

                davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
223             Guyana      3.6765      9.5220    790.326   214969
224      French Guiana      3.6685      9.5015    306.448    83534
225           Suriname      3.6125      9.3564    591.800   163820
226          Australia      3.3526      8.6832  25788.215  7692024
227            Iceland      3.3335      8.6338    343.353   103000
228            Namibia      3.1338      8.1166   2587.344   825615
229     Western Sahara      2.3003      5.9577    611.875   266000
230           Mongolia      2.1286      5.5129   3329.289  1564110
231   Falkland Islands      0.2902      0.7517      3.533    12173
232          Greenland      0.0263      0.0680     56.877  2166086

### 3-VAZIFA. DF dan 10, 20, 100, 200-indekslarda turgan davlatlarni alohida DF ko'rinishida chiqaring.

In [19]:
df.iloc[[10,20,100,200]]

          davlat  zichlik_km  zichlik_mi       aholi  maydoni
rank
11    Bangladesh   1126.9465   2918.7915  166303.498   147570
21    San Marino    557.6557   1444.3284      34.017       61
101        Benin    110.5560    286.3401   12451.040   112622
201     Paraguay     17.7495     45.9712    7219.638   406752

### 4-VAZIFA. Davlatlar orasida `Uzbekistan`, `Hong-Kong`, `Antartica` borligini tekshiring

In [24]:
selected_countries = ['Uzbekistan', 'Hong-Kong', 'Antartica']
exist = df[df['davlat'].isin(selected_countries)]

print(exist)

          davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
133   Uzbekistan     75.8511    196.4542  33935.763   447400

### 5-VAZIFA.
#### 5.1 DFning `davlat` nomli ustunini uning indeksi qilib belgilang.
#### 5.2 `davlat` ustunini tashlab yuboring.
#### 5.3 DFni davlat nomi bo'yicha tartiblang

In [66]:
# 5.1 DFning davlat nomli ustunini uning indeksi qilib belgilang.

df_new.set_index('davlat' , inplace = False)

                  zichlik_km  zichlik_mi     aholi     area
davlat
Macau             21946.4667  56841.3487   658.394       30
Monaco            19755.5000  51166.7450    39.511        2
Singapore          8305.1915  21510.4461  5896.686      710
Hong Kong          6841.3134  17719.0017  7552.810     1104
Gibraltar          5616.3333  14546.3033    33.698        6
...                      ...         ...       ...      ...
Namibia               3.1338      8.1166  2587.344   825615
Western Sahara        2.3003      5.9577   611.875   266000
Mongolia              2.1286      5.5129  3329.289  1564110
Falkland Islands      0.2902      0.7517     3.533    12173
Greenland             0.0263      0.0680    56.877  2166086

[232 rows x 4 columns]

In [30]:
# 5.2 davlat ustunini tashlab yuboring.
dropped_data = df.drop(columns = 'davlat')
dropped_data

      zichlik_km  zichlik_mi     aholi  maydoni
rank
1     21946.4667  56841.3487   658.394       30
2     19755.5000  51166.7450    39.511        2
3      8305.1915  21510.4461  5896.686      710
4      6841.3134  17719.0017  7552.810     1104
5      5616.3333  14546.3033    33.698        6
...          ...         ...       ...      ...
228       3.1338      8.1166  2587.344   825615
229       2.3003      5.9577   611.875   266000
230       2.1286      5.5129  3329.289  1564110
231       0.2902      0.7517     3.533    12173
232       0.0263      0.0680    56.877  2166086

[232 rows x 4 columns]

In [25]:
# 5.3 DFni davlat nomi bo'yicha tartiblang
df.sort_values(by = 'davlat')

                 davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
149         Afghanistan     61.0757    158.1862  39835.428   652230
111             Albania     99.9351    258.8318   2872.933    28748
198             Algeria     18.7328     48.5179  44616.624  2381741
50       American Samoa    276.8844    717.1307     55.100      199
78              Andorra    165.2885    428.0971     77.355      468
...                 ...         ...         ...        ...      ...
131   Wallis and Futuna     78.1268    202.3483     11.094      142
229      Western Sahara      2.3003      5.9577    611.875   266000
151               Yemen     57.7509    149.5749  30490.640   527968
188              Zambia     25.1400     65.1125  18920.651   752612
173            Zimbabwe     38.6229    100.0333  15092.171   390757

[232 rows x 5 columns]

In [ ]:
#@title Kutilayotgan natija

                zichlik_km  zichlik_mi      aholi  maydoni
davlat
Afghanistan        61.0757    158.1862  39835.428   652230
Albania            99.9351    258.8318   2872.933    28748
Algeria            18.7328     48.5179  44616.624  2381741
American Samoa    276.8844    717.1307     55.100      199
Andorra           165.2885    428.0971     77.355      468

### 6-VAZIFA. DF dan `Uzbekistan`, `Malaysia`, `South Korea`, `France` davlatlari `aholi` va `maydoni` ustunlari bilan alohida DF ko'rinishida ajratib oling.

In [81]:
df_selct = ['Uzbekistan', 'Malaysia', 'South' 'Korea', 'France']
df_sel = ['aholi' , 'maydoni']

selected_rows = df_new.loc[df['davlat'].isin(df_selct)]

result = selected_rows[df_sel]
result

          aholi  maydoni
rank
95    65426.179   551695
113   32776.194   330803
133   33935.763   447400

In [ ]:
#@title O'xshash natija (boshqa davlatlar uchun)

                 aholi  maydoni
davlat
Singapore     5896.686      710
North Korea  25887.041   120538
Germany      83900.473   357114
Kazakhstan   18994.962  2724900

### 7-VAZIFA. Asl DFning `aholi` ustuni qiymatlarini 1000 ga ko'paytiring.

In [89]:
df[df_new['aholi'] * 1000]

KeyError: "None of [Index([(658394.0, 39511.0, 5896686.0, 7552810.0, 33698.0, 1748296.0, 543617.0, 442784.0, 43412.0, 62090.0, 166303498.0, 5222748.0, 800.0, 279515.0, 39234.0, 287711.0, 23855010.0, 6769146.0, 1273433.0, 107204.0, 34017.0, 10876.0, 51305186.0, 13276513.0, 888451.0, 9907.0, 11931.0, 12255433.0, 1393409038.0, 8789774.0, 11541685.0, 17173099.0, 11632326.0, 164798.0, 901686.0, 126050804.0, 374745.0, 59610.0, 113021.0, 21497310.0, 111046913.0, 2828255.0, 170179.0, 6518499.0, 104226.0, 184400.0, 98168833.0, 111263.0, 68207116.0, 55100.0, 1403375.0, 2973463.0, 225199937.0, 2930528.0, 66497.0, 400020.0, 634814.0, 4328550.0, 38250.0, 83900473.0, 2486945.0, 223368.0, 211400708.0, 10953703.0, 98731.0, 98908.0, 25887041.0, 8715494.0, 53544.0, 29674920.0, 30421.0, 60367477.0, 47123531.0, 18249860.0, 15117.0, 19647684.0, 116254.0, 77355.0, 121392.0, 85410.0, 8478250.0, 1444216107.0, 276361783.0, 106760.0, 561898.0, 69950850.0, 10724555.0, 5813298.0, 31732129.0, 1215584.0, 57917.0, 37797005.0, 9991089.0, 4024019.0, 65426179.0, 10223342.0, 10269021.0, 1373.0, 8141343.0, 5460721.0, ...)], dtype='object')] are in the [columns]"

In [ ]:
#@title Kutilgan natija

                zichlik_km  zichlik_mi       aholi  maydoni
davlat
Afghanistan        61.0757    158.1862  39835428.0   652230
Albania            99.9351    258.8318   2872933.0    28748
Algeria            18.7328     48.5179  44616624.0  2381741
American Samoa    276.8844    717.1307     55100.0      199
Andorra           165.2885    428.0971     77355.0      468

DF ni `aholi` ustuni bo'yicha kamayish tartibida tahlang va aholisi eng kam 10 ta davlatni chiqaring.

In [96]:
df_new_sorted = df_new.sort_values(by='aholi', ascending=False)

df_new_sorted.head(10)

,davlat,zichlik_km,zichlik_mi,aholi,maydoni,aholi_in_thousands
rank,,,,,,
82,China,148.7815,385.3441,1444216.107,9706961,1.444216e+09
29,India,423.8391,1097.7432,1393409.038,3287590,1.393409e+09
174,United States,35.5200,91.9968,332915.073,9372610,3.329151e+08
83,Indonesia,145.1046,375.8210,276361.783,1904569,2.763618e+08
53,Pakistan,255.3542,661.3674,225199.937,881912,2.251999e+08
189,Brazil,25.1291,65.0843,213993.437,8515767,2.139934e+08
63,Nigeria,228.8461,592.7114,211400.708,923768,2.114007e+08
11,Bangladesh,1126.9465,2918.7915,166303.498,147570,1.663035e+08
214,Russia,8.5337,22.1024,145912.025,17098242,1.459120e+08
144,Mexico,66.3123,171.7488,130262.216,1964375,1.302622e+08

In [106]:
# df_min = df_new.loc[[df_new['aholi'].idxmin()]]

df_new_sorted = df.sort_values(by='aholi', ascending=True)

df_new_sorted.head(10)

,davlat,zichlik_km,zichlik_mi,aholi,maydoni,aholi_in_thousands
rank,,,,,,
13,Vatican City,800.0000,2072.0000,0.800,1,800.0
98,Tokelau,114.4167,296.3392,1.373,12,1373.0
218,Niue,6.2269,16.1277,1.619,260,1619.0
231,Falkland Islands,0.2902,0.7517,3.533,12173,3533.0
161,Montserrat,48.7941,126.3768,4.977,102,4977.0
191,Saint Pierre and Miquelon,23.8264,61.7105,5.766,242,5766.0
26,Saint Barthelemy,471.7619,1221.8633,9.907,21,9907.0
22,Nauru,517.9048,1341.3733,10.876,21,10876.0
131,Wallis and Futuna,78.1268,202.3483,11.094,142,11094.0
27,Tuvalu,458.8846,1188.5112,11.931,26,11931.0

### 8-VAZIFA. DFni `maydoni` bo'yicha reytinglang (rank) va reytinglarni yangi `rank` ustuniga yozing.

In [109]:
df_new['rank'] = df['maydoni'].rank()
df_new

,davlat,zichlik_km,zichlik_mi,aholi,maydoni,aholi_in_thousands,rank
rank,,,,,,,
1,Macau,21946.4667,56841.3487,658.394,30,658394.0,8.0
2,Monaco,19755.5000,51166.7450,39.511,2,39511.0,2.0
3,Singapore,8305.1915,21510.4461,5896.686,710,5896686.0,43.0
4,Hong Kong,6841.3134,17719.0017,7552.810,1104,7552810.0,50.0
5,Gibraltar,5616.3333,14546.3033,33.698,6,33698.0,3.0
...,...,...,...,...,...,...,...
228,Namibia,3.1338,8.1166,2587.344,825615,2587344.0,198.0
229,Western Sahara,2.3003,5.9577,611.875,266000,611875.0,155.0
230,Mongolia,2.1286,5.5129,3329.289,1564110,3329289.0,214.0
231,Falkland Islands,0.2902,0.7517,3.533,12173,3533.0,70.0
232,Greenland,0.0263,0.0680,56.877,2166086,56877.0,221.0

In [ ]:
#@title Kutilgan natija

                   zichlik_km  zichlik_mi       aholi  maydoni   rank
davlat
Afghanistan           61.0757    158.1862  39835428.0   652230  192.0
Albania               99.9351    258.8318   2872933.0    28748   89.0
Algeria               18.7328     48.5179  44616624.0  2381741  223.0
American Samoa       276.8844    717.1307     55100.0      199   20.0
Andorra              165.2885    428.0971     77355.0      468   38.0
...                       ...         ...         ...      ...    ...
Wallis and Futuna     78.1268    202.3483     11094.0      142   15.0
Western Sahara         2.3003      5.9577    611875.0   266000  155.0
Yemen                 57.7509    149.5749  30490640.0   527968  183.0
Zambia                25.1400     65.1125  18920651.0   752612  194.0
Zimbabwe              38.6229    100.0333  15092171.0   390757  172.0

[232 rows x 5 columns]

#### `Uzbekistan`, `United Kingdom`, `Indonesia` davlatlari alohida df ko'rinishida chiqaring

In [112]:
selected_cs = ['Uzbekistan', 'United Kingdom', 'Indonesia']

df2 = df_new[df_new['davlat'].isin(selected_cs)]

df2.set_index('davlat')

,zichlik_km,zichlik_mi,aholi,maydoni,aholi_in_thousands,rank
davlat,,,,,,
United Kingdom,280.8033,727.2805,68207.116,242900,68207116.0,153.0
Indonesia,145.1046,375.8210,276361.783,1904569,276361783.0,218.0
Uzbekistan,75.8511,196.4542,33935.763,447400,33935763.0,176.0

In [ ]:
#@title O'xshash natija (boshqa davlatlar uchun)

               zichlik_km  zichlik_mi        aholi  maydoni   rank
davlat
Turkmenistan      12.5342     32.4635    6117924.0   488100  180.0
United States     35.5200     91.9968  332915073.0  9372610  229.0
Vietnam          296.3927    767.6572   98168833.0   331212  166.0

### 9-VAZIFA. DFni `davlat` nomi bo'yicha tartiblang.

In [113]:
df_new.sort_values(by = 'davlat')

,davlat,zichlik_km,zichlik_mi,aholi,maydoni,aholi_in_thousands,rank
rank,,,,,,,
149,Afghanistan,61.0757,158.1862,39835.428,652230,39835428.0,192.0
111,Albania,99.9351,258.8318,2872.933,28748,2872933.0,89.0
198,Algeria,18.7328,48.5179,44616.624,2381741,44616624.0,223.0
50,American Samoa,276.8844,717.1307,55.100,199,55100.0,20.0
78,Andorra,165.2885,428.0971,77.355,468,77355.0,38.0
...,...,...,...,...,...,...,...
131,Wallis and Futuna,78.1268,202.3483,11.094,142,11094.0,15.0
229,Western Sahara,2.3003,5.9577,611.875,266000,611875.0,155.0
151,Yemen,57.7509,149.5749,30490.640,527968,30490640.0,183.0
188,Zambia,25.1400,65.1125,18920.651,752612,18920651.0,194.0
173,Zimbabwe,38.6229,100.0333,15092.171,390757,15092171.0,172.0

In [ ]:
#@title Kutilgan natija

                zichlik_km  zichlik_mi       aholi  maydoni   rank
davlat
Afghanistan        61.0757    158.1862  39835428.0   652230  192.0
Albania            99.9351    258.8318   2872933.0    28748   89.0
Algeria            18.7328     48.5179  44616624.0  2381741  223.0
American Samoa    276.8844    717.1307     55100.0      199   20.0
Andorra           165.2885    428.0971     77355.0      468   38.0

#### DFdan 10,50,100,200-o'rinda turgan davlatlarni alohida DF ko'rinishida chiqaring

In [114]:
df_new.loc[[10,50,100,200]]

,davlat,zichlik_km,zichlik_mi,aholi,maydoni,aholi_in_thousands,rank
rank,,,,,,,
10,Bermuda,1149.8148,2978.0204,62.090,54,62090.0,11.0
50,American Samoa,276.8844,717.1307,55.100,199,55100.0,20.0
100,Slovakia,111.3592,288.4203,5460.721,49037,5460721.0,103.0
200,New Zealand,17.9713,46.5457,4860.643,270467,4860643.0,157.0

In [ ]:
#@title O'xshash natija (boshqa qatorlar uchun)

                              zichlik_km  zichlik_mi     aholi  maydoni  rank
davlat
Belize                           17.6310     45.6643  404914.0    22966  82.0
French Polynesia                 67.8018    175.6066  282530.0     4167  60.0
Guadeloupe                      245.7125    636.3955  400020.0     1628  53.0
United States Virgin Islands    300.3631    777.9405  104226.0      347  29.0

### 10-VAZIFA. Quyidagi davlatlarning `aholi` sonini oddiy son ko'rinishida chiqaring:
- `Malaysia`
- `Nigeria`
- `Nepal`
- `Italy`

In [120]:
countries = ['Malaysia' ,  'Nigeria' , 'Nepal' , 'Italy']

sumpo_cs  = df_new[df_new['davlat'].isin(countries)]
np.sum(sumpo_cs.aholi)

334219.29900000006

In [ ]:
#@title o'xshash natija (`Uzbekistan` uchun)

33935763.0